/*
SET GLOBAL local_infile=1;

LOAD DATA LOCAL INFILE 'D:/Universidad/5to_semestre/bases_de_datos/Lab2/lab2_regiones_municipios_departamentos.txt' INTO TABLE municipios_temp FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n'; 

SELECT CONCAT('("', departamento, '","', municipio, '")') FROM municipios_temp; 
*/

DROP PROCEDURE IF EXISTS ADD_CITY; 

DELIMITER //

CREATE PROCEDURE ADD_CITY(
	IN depto VARCHAR(255), 
	IN mun VARCHAR(255)
)
BEGIN
	
	SELECT id_departamento INTO @id_depto FROM departamentos 
		WHERE departamentos.departamento = depto; 
	
	INSERT INTO ciudades(id_departamento, ciudad) VALUES(@id_depto, mun); 
	
END; 

CALL ADD_CITY("Archipiélago de San Andrés, Providencia y Santa Catalina","Providencia");
CALL ADD_CITY("Archipiélago de San Andrés, Providencia y Santa Catalina","San Andrés");
CALL ADD_CITY("Atlántico","Baranoa");
CALL ADD_CITY("Atlántico","Barranquilla");
CALL ADD_CITY("Atlántico","Campo de La Cruz");
CALL ADD_CITY("Atlántico","Candelaria");
CALL ADD_CITY("Atlántico","Galapa");
CALL ADD_CITY("Atlántico","Juan de Acosta");
CALL ADD_CITY("Atlántico","Luruaco");
CALL ADD_CITY("Atlántico","Malambo");
CALL ADD_CITY("Atlántico","Manatí");
CALL ADD_CITY("Atlántico","Palmar de Varela");
CALL ADD_CITY("Atlántico","Piojó");
CALL ADD_CITY("Atlántico","Polonuevo");
CALL ADD_CITY("Atlántico","Ponedera");
CALL ADD_CITY("Atlántico","Puerto Colombia");
CALL ADD_CITY("Atlántico","Repelón");
CALL ADD_CITY("Atlántico","Sabanagrande");
CALL ADD_CITY("Atlántico","Sabanalarga");
CALL ADD_CITY("Atlántico","Santa Lucía");
CALL ADD_CITY("Atlántico","Santo Tomás");
CALL ADD_CITY("Atlántico","Soledad");
CALL ADD_CITY("Atlántico","Suan");
CALL ADD_CITY("Atlántico","Tubará");
CALL ADD_CITY("Atlántico","Usiacurí");
CALL ADD_CITY("Bolívar","Achí");
CALL ADD_CITY("Bolívar","Altos del Rosario");
CALL ADD_CITY("Bolívar","Arenal");
CALL ADD_CITY("Bolívar","Arjona");
CALL ADD_CITY("Bolívar","Arroyohondo");
CALL ADD_CITY("Bolívar","Barranco de Loba");
CALL ADD_CITY("Bolívar","Calamar");
CALL ADD_CITY("Bolívar","Cantagallo");
CALL ADD_CITY("Bolívar","Cartagena");
CALL ADD_CITY("Bolívar","Cicuco");
CALL ADD_CITY("Bolívar","Clemencia");
CALL ADD_CITY("Bolívar","Córdoba");
CALL ADD_CITY("Bolívar","El Carmen de Bolívar");
CALL ADD_CITY("Bolívar","El Guamo");
CALL ADD_CITY("Bolívar","El Peñón");
CALL ADD_CITY("Bolívar","Hatillo de Loba");
CALL ADD_CITY("Bolívar","Magangué");
CALL ADD_CITY("Bolívar","Mahates");
CALL ADD_CITY("Bolívar","Margarita");
CALL ADD_CITY("Bolívar","María la Baja");
CALL ADD_CITY("Bolívar","Mompós");
CALL ADD_CITY("Bolívar","Montecristo");
CALL ADD_CITY("Bolívar","Morales");
CALL ADD_CITY("Bolívar","Norosí");
CALL ADD_CITY("Bolívar","Pinillos");
CALL ADD_CITY("Bolívar","Regidor");
CALL ADD_CITY("Bolívar","Río Viejo");
CALL ADD_CITY("Bolívar","San Cristóbal");
CALL ADD_CITY("Bolívar","San Estanislao");
CALL ADD_CITY("Bolívar","San Fernando");
CALL ADD_CITY("Bolívar","San Jacinto");
CALL ADD_CITY("Bolívar","San Jacinto del Cauca");
CALL ADD_CITY("Bolívar","San Juan Nepomuceno");
CALL ADD_CITY("Bolívar","San Martín de Loba");
CALL ADD_CITY("Bolívar","San Pablo de Borbur");
CALL ADD_CITY("Bolívar","Santa Catalina");
CALL ADD_CITY("Bolívar","Santa Rosa");
CALL ADD_CITY("Bolívar","Santa Rosa del Sur");
CALL ADD_CITY("Bolívar","Simití");
CALL ADD_CITY("Bolívar","Soplaviento");
CALL ADD_CITY("Bolívar","Talaigua Nuevo");
CALL ADD_CITY("Bolívar","Tiquisio");
CALL ADD_CITY("Bolívar","Turbaco");
CALL ADD_CITY("Bolívar","Turbaná");
CALL ADD_CITY("Bolívar","Villanueva");
CALL ADD_CITY("Bolívar","Zambrano");
CALL ADD_CITY("Cesar","Aguachica");
CALL ADD_CITY("Cesar","Agustín Codazzi");
CALL ADD_CITY("Cesar","Astrea");
CALL ADD_CITY("Cesar","Becerril");
CALL ADD_CITY("Cesar","Bosconia");
CALL ADD_CITY("Cesar","Chimichagua");
CALL ADD_CITY("Cesar","Chiriguaná");
CALL ADD_CITY("Cesar","Curumaní");
CALL ADD_CITY("Cesar","El Copey");
CALL ADD_CITY("Cesar","El Paso");
CALL ADD_CITY("Cesar","Gamarra");
CALL ADD_CITY("Cesar","González");
CALL ADD_CITY("Cesar","La Gloria");
CALL ADD_CITY("Cesar","La Jagua de Ibirico");
CALL ADD_CITY("Cesar","La Paz");
CALL ADD_CITY("Cesar","Manaure");
CALL ADD_CITY("Cesar","Pailitas");
CALL ADD_CITY("Cesar","Pelaya");
CALL ADD_CITY("Cesar","Pueblo Bello");
CALL ADD_CITY("Cesar","Río de Oro");
CALL ADD_CITY("Cesar","San Alberto");
CALL ADD_CITY("Cesar","San Diego");
CALL ADD_CITY("Cesar","San Martín");
CALL ADD_CITY("Cesar","Tamalameque");
CALL ADD_CITY("Cesar","Valledupar");
CALL ADD_CITY("Córdoba","Ayapel");
CALL ADD_CITY("Córdoba","Buenavista");
CALL ADD_CITY("Córdoba","Canalete");
CALL ADD_CITY("Córdoba","Cereté");
CALL ADD_CITY("Córdoba","Chimá");
CALL ADD_CITY("Córdoba","Chinú");
CALL ADD_CITY("Córdoba","Ciénaga de Oro");
CALL ADD_CITY("Córdoba","Cotorra");
CALL ADD_CITY("Córdoba","La Apartada");
CALL ADD_CITY("Córdoba","Lorica");
CALL ADD_CITY("Córdoba","Los Córdobas");
CALL ADD_CITY("Córdoba","Momil");
CALL ADD_CITY("Córdoba","Montelíbano");
CALL ADD_CITY("Córdoba","Montería");
CALL ADD_CITY("Córdoba","Moñitos");
CALL ADD_CITY("Córdoba","Planeta Rica");
CALL ADD_CITY("Córdoba","Pueblo Nuevo");
CALL ADD_CITY("Córdoba","Puerto Escondido");
CALL ADD_CITY("Córdoba","Puerto Libertador");
CALL ADD_CITY("Córdoba","Purísima");
CALL ADD_CITY("Córdoba","Sahagún");
CALL ADD_CITY("Córdoba","San Andrés Sotavento");
CALL ADD_CITY("Córdoba","San Antero");
CALL ADD_CITY("Córdoba","San Bernardo del Viento");
CALL ADD_CITY("Córdoba","San Carlos");
CALL ADD_CITY("Córdoba","San José de Uré");
CALL ADD_CITY("Córdoba","San Pelayo");
CALL ADD_CITY("Córdoba","Tierralta");
CALL ADD_CITY("Córdoba","Tuchín");
CALL ADD_CITY("Córdoba","Valencia");
CALL ADD_CITY("La Guajira","Albania");
CALL ADD_CITY("La Guajira","Barrancas");
CALL ADD_CITY("La Guajira","Dibula");
CALL ADD_CITY("La Guajira","Distracción");
CALL ADD_CITY("La Guajira","El Molino");
CALL ADD_CITY("La Guajira","Fonseca");
CALL ADD_CITY("La Guajira","Hatonuevo");
CALL ADD_CITY("La Guajira","La Jagua del Pilar");
CALL ADD_CITY("La Guajira","Maicao");
CALL ADD_CITY("La Guajira","Manaure");
CALL ADD_CITY("La Guajira","Riohacha");
CALL ADD_CITY("La Guajira","San Juan del Cesar");
CALL ADD_CITY("La Guajira","Uribia");
CALL ADD_CITY("La Guajira","Urumita");
CALL ADD_CITY("La Guajira","Villanueva");
CALL ADD_CITY("Magdalena","Algarrobo");
CALL ADD_CITY("Magdalena","Aracataca");
CALL ADD_CITY("Magdalena","Ariguaní");
CALL ADD_CITY("Magdalena","Cerro San Antonio");
CALL ADD_CITY("Magdalena","Chivolo");
CALL ADD_CITY("Magdalena","Ciénaga");
CALL ADD_CITY("Magdalena","Concordia");
CALL ADD_CITY("Magdalena","El Banco");
CALL ADD_CITY("Magdalena","El Piñon");
CALL ADD_CITY("Magdalena","El Retén");
CALL ADD_CITY("Magdalena","Fundación");
CALL ADD_CITY("Magdalena","Guamal");
CALL ADD_CITY("Magdalena","Nueva Granada");
CALL ADD_CITY("Magdalena","Pedraza");
CALL ADD_CITY("Magdalena","Pijiño del Carmen");
CALL ADD_CITY("Magdalena","Pivijay");
CALL ADD_CITY("Magdalena","Plato");
CALL ADD_CITY("Magdalena","Pueblo Viejo");
CALL ADD_CITY("Magdalena","Remolino");
CALL ADD_CITY("Magdalena","Sabanas de San Angel");
CALL ADD_CITY("Magdalena","Salamina");
CALL ADD_CITY("Magdalena","San Sebastián de Buenavista");
CALL ADD_CITY("Magdalena","San Zenón");
CALL ADD_CITY("Magdalena","Santa Ana");
CALL ADD_CITY("Magdalena","Santa Bárbara de Pinto");
CALL ADD_CITY("Magdalena","Santa Marta");
CALL ADD_CITY("Magdalena","Sitionuevo");
CALL ADD_CITY("Magdalena","Tenerife");
CALL ADD_CITY("Magdalena","Zapayán");
CALL ADD_CITY("Magdalena","Zona Bananera");
CALL ADD_CITY("Sucre","Buenavista");
CALL ADD_CITY("Sucre","Caimito");
CALL ADD_CITY("Sucre","Chalán");
CALL ADD_CITY("Sucre","Coloso");
CALL ADD_CITY("Sucre","Corozal");
CALL ADD_CITY("Sucre","Coveñas");
CALL ADD_CITY("Sucre","El Roble");
CALL ADD_CITY("Sucre","Galeras");
CALL ADD_CITY("Sucre","Guaranda");
CALL ADD_CITY("Sucre","La Unión");
CALL ADD_CITY("Sucre","Los Palmitos");
CALL ADD_CITY("Sucre","Majagual");
CALL ADD_CITY("Sucre","Morroa");
CALL ADD_CITY("Sucre","Ovejas");
CALL ADD_CITY("Sucre","Palmito");
CALL ADD_CITY("Sucre","Sampués");
CALL ADD_CITY("Sucre","San Benito Abad");
CALL ADD_CITY("Sucre","San Juan de Betulia");
CALL ADD_CITY("Sucre","San Luis de Sincé");
CALL ADD_CITY("Sucre","San Marcos");
CALL ADD_CITY("Sucre","San Onofre");
CALL ADD_CITY("Sucre","San Pedro");
CALL ADD_CITY("Sucre","Santiago de Tolú");
CALL ADD_CITY("Sucre","Sincelejo");
CALL ADD_CITY("Sucre","Sucre");
CALL ADD_CITY("Sucre","Tolú Viejo");
CALL ADD_CITY("Bogotá D.C.","Bogotá D.C.");
CALL ADD_CITY("Boyacá","Almeida");
CALL ADD_CITY("Boyacá","Aquitania");
CALL ADD_CITY("Boyacá","Arcabuco");
CALL ADD_CITY("Boyacá","Belén");
CALL ADD_CITY("Boyacá","Berbeo");
CALL ADD_CITY("Boyacá","Betéitiva");
CALL ADD_CITY("Boyacá","Boavita");
CALL ADD_CITY("Boyacá","Boyacá");
CALL ADD_CITY("Boyacá","Briceño");
CALL ADD_CITY("Boyacá","Buena Vista");
CALL ADD_CITY("Boyacá","Busbanzá");
CALL ADD_CITY("Boyacá","Caldas");
CALL ADD_CITY("Boyacá","Campohermoso");
CALL ADD_CITY("Boyacá","Cerinza");
CALL ADD_CITY("Boyacá","Chinavita");
CALL ADD_CITY("Boyacá","Chiquinquirá");
CALL ADD_CITY("Boyacá","Chíquiza");
CALL ADD_CITY("Boyacá","Chiscas");
CALL ADD_CITY("Boyacá","Chita");
CALL ADD_CITY("Boyacá","Chitaraque");
CALL ADD_CITY("Boyacá","Chivatá");
CALL ADD_CITY("Boyacá","Chivor");
CALL ADD_CITY("Boyacá","Ciénega");
CALL ADD_CITY("Boyacá","Cómbita");
CALL ADD_CITY("Boyacá","Coper");
CALL ADD_CITY("Boyacá","Corrales");
CALL ADD_CITY("Boyacá","Covarachía");
CALL ADD_CITY("Boyacá","Cubará");
CALL ADD_CITY("Boyacá","Cucaita");
CALL ADD_CITY("Boyacá","Cuítiva");
CALL ADD_CITY("Boyacá","Duitama");
CALL ADD_CITY("Boyacá","El Cocuy");
CALL ADD_CITY("Boyacá","El Espino");
CALL ADD_CITY("Boyacá","Firavitoba");
CALL ADD_CITY("Boyacá","Floresta");
CALL ADD_CITY("Boyacá","Gachantivá");
CALL ADD_CITY("Boyacá","Gameza");
CALL ADD_CITY("Boyacá","Garagoa");
CALL ADD_CITY("Boyacá","Guacamayas");
CALL ADD_CITY("Boyacá","Guateque");
CALL ADD_CITY("Boyacá","Guayatá");
CALL ADD_CITY("Boyacá","Güicán");
CALL ADD_CITY("Boyacá","Iza");
CALL ADD_CITY("Boyacá","Jenesano");
CALL ADD_CITY("Boyacá","Jericó");
CALL ADD_CITY("Boyacá","La Capilla");
CALL ADD_CITY("Boyacá","La Uvita");
CALL ADD_CITY("Boyacá","La Victoria");
CALL ADD_CITY("Boyacá","Labranzagrande");
CALL ADD_CITY("Boyacá","Macanal");
CALL ADD_CITY("Boyacá","Maripí");
CALL ADD_CITY("Boyacá","Miraflores");
CALL ADD_CITY("Boyacá","Mongua");
CALL ADD_CITY("Boyacá","Monguí");
CALL ADD_CITY("Boyacá","Moniquirá");
CALL ADD_CITY("Boyacá","Motavita");
CALL ADD_CITY("Boyacá","Muzo");
CALL ADD_CITY("Boyacá","Nobsa");
CALL ADD_CITY("Boyacá","Nuevo Colón");
CALL ADD_CITY("Boyacá","Oicatá");
CALL ADD_CITY("Boyacá","Otanche");
CALL ADD_CITY("Boyacá","Pachavita");
CALL ADD_CITY("Boyacá","Páez");
CALL ADD_CITY("Boyacá","Paipa");
CALL ADD_CITY("Boyacá","Pajarito");
CALL ADD_CITY("Boyacá","Panqueba");
CALL ADD_CITY("Boyacá","Pauna");
CALL ADD_CITY("Boyacá","Paya");
CALL ADD_CITY("Boyacá","Paz de Río");
CALL ADD_CITY("Boyacá","Pesca");
CALL ADD_CITY("Boyacá","Pisba");
CALL ADD_CITY("Boyacá","Puerto Boyacá");
CALL ADD_CITY("Boyacá","Quípama");
CALL ADD_CITY("Boyacá","Ramiriquí");
CALL ADD_CITY("Boyacá","Ráquira");
CALL ADD_CITY("Boyacá","Rondón");
CALL ADD_CITY("Boyacá","Saboyá");
CALL ADD_CITY("Boyacá","Sáchica");
CALL ADD_CITY("Boyacá","Samacá");
CALL ADD_CITY("Boyacá","San Eduardo");
CALL ADD_CITY("Boyacá","San José de Pare");
CALL ADD_CITY("Boyacá","San Luis de Gaceno");
CALL ADD_CITY("Boyacá","San Mateo");
CALL ADD_CITY("Boyacá","San Miguel de Sema");
CALL ADD_CITY("Boyacá","San Pablo de Borbur");
CALL ADD_CITY("Boyacá","Socha");
CALL ADD_CITY("Boyacá","Santa María");
CALL ADD_CITY("Boyacá","Santa Rosa de Viterbo");
CALL ADD_CITY("Boyacá","Santa Sofía");
CALL ADD_CITY("Boyacá","Santana");
CALL ADD_CITY("Boyacá","Sativanorte");
CALL ADD_CITY("Boyacá","Sativasur");
CALL ADD_CITY("Boyacá","Siachoque");
CALL ADD_CITY("Boyacá","Soatá");
CALL ADD_CITY("Boyacá","Socotá");
CALL ADD_CITY("Boyacá","Sogamoso");
CALL ADD_CITY("Boyacá","Somondoco");
CALL ADD_CITY("Boyacá","Sora");
CALL ADD_CITY("Boyacá","Soracá");
CALL ADD_CITY("Boyacá","Sotaquirá");
CALL ADD_CITY("Boyacá","Susacón");
CALL ADD_CITY("Boyacá","Sutamarchán");
CALL ADD_CITY("Boyacá","Sutatenza");
CALL ADD_CITY("Boyacá","Tasco");
CALL ADD_CITY("Boyacá","Tenza");
CALL ADD_CITY("Boyacá","Tibaná");
CALL ADD_CITY("Boyacá","Tibasosa");
CALL ADD_CITY("Boyacá","Tinjacá");
CALL ADD_CITY("Boyacá","Tipacoque");
CALL ADD_CITY("Boyacá","Toca");
CALL ADD_CITY("Boyacá","Togüí");
CALL ADD_CITY("Boyacá","Tópaga");
CALL ADD_CITY("Boyacá","Tota");
CALL ADD_CITY("Boyacá","Tunja");
CALL ADD_CITY("Boyacá","Tununguá");
CALL ADD_CITY("Boyacá","Turmequé");
CALL ADD_CITY("Boyacá","Tuta");
CALL ADD_CITY("Boyacá","Tutazá");
CALL ADD_CITY("Boyacá","Umbita");
CALL ADD_CITY("Boyacá","Ventaquemada");
CALL ADD_CITY("Boyacá","Villa de Leyva");
CALL ADD_CITY("Boyacá","Viracachá");
CALL ADD_CITY("Boyacá","Zetaquira");
CALL ADD_CITY("Cundinamarca","Agua de Dios");
CALL ADD_CITY("Cundinamarca","Albán");
CALL ADD_CITY("Cundinamarca","Anapoima");
CALL ADD_CITY("Cundinamarca","Anolaima");
CALL ADD_CITY("Cundinamarca","Apulo");
CALL ADD_CITY("Cundinamarca","Arbeláez");
CALL ADD_CITY("Cundinamarca","Beltrán");
CALL ADD_CITY("Cundinamarca","Bituima");
CALL ADD_CITY("Cundinamarca","Bojacá");
CALL ADD_CITY("Cundinamarca","Cabrera");
CALL ADD_CITY("Cundinamarca","Cachipay");
CALL ADD_CITY("Cundinamarca","Cajicá");
CALL ADD_CITY("Cundinamarca","Caparrapí");
CALL ADD_CITY("Cundinamarca","Caqueza");
CALL ADD_CITY("Cundinamarca","Carmen de Carupa");
CALL ADD_CITY("Cundinamarca","Chaguaní");
CALL ADD_CITY("Cundinamarca","Chía");
CALL ADD_CITY("Cundinamarca","Chipaque");
CALL ADD_CITY("Cundinamarca","Choachí");
CALL ADD_CITY("Cundinamarca","Chocontá");
CALL ADD_CITY("Cundinamarca","Cogua");
CALL ADD_CITY("Cundinamarca","Cota");
CALL ADD_CITY("Cundinamarca","Cucunubá");
CALL ADD_CITY("Cundinamarca","El Colegio");
CALL ADD_CITY("Cundinamarca","El Peñón");
CALL ADD_CITY("Cundinamarca","El Rosal");
CALL ADD_CITY("Cundinamarca","Facatativá");
CALL ADD_CITY("Cundinamarca","Fomeque");
CALL ADD_CITY("Cundinamarca","Fosca");
CALL ADD_CITY("Cundinamarca","Funza");
CALL ADD_CITY("Cundinamarca","Fúquene");
CALL ADD_CITY("Cundinamarca","Fusagasugá");
CALL ADD_CITY("Cundinamarca","Gachala");
CALL ADD_CITY("Cundinamarca","Gachancipá");
CALL ADD_CITY("Cundinamarca","Gachetá");
CALL ADD_CITY("Cundinamarca","Gama");
CALL ADD_CITY("Cundinamarca","Girardot");
CALL ADD_CITY("Cundinamarca","Granada");
CALL ADD_CITY("Cundinamarca","Guachetá");
CALL ADD_CITY("Cundinamarca","Guaduas");
CALL ADD_CITY("Cundinamarca","Guasca");
CALL ADD_CITY("Cundinamarca","Guataquí");
CALL ADD_CITY("Cundinamarca","Guatavita");
CALL ADD_CITY("Cundinamarca","Guayabal de Siquima");
CALL ADD_CITY("Cundinamarca","Guayabetal");
CALL ADD_CITY("Cundinamarca","Gutiérrez");
CALL ADD_CITY("Cundinamarca","Jerusalén");
CALL ADD_CITY("Cundinamarca","Junín");
CALL ADD_CITY("Cundinamarca","La Calera");
CALL ADD_CITY("Cundinamarca","La Mesa");
CALL ADD_CITY("Cundinamarca","La Palma");
CALL ADD_CITY("Cundinamarca","La Peña");
CALL ADD_CITY("Cundinamarca","La Vega");
CALL ADD_CITY("Cundinamarca","Lenguazaque");
CALL ADD_CITY("Cundinamarca","Macheta");
CALL ADD_CITY("Cundinamarca","Madrid");
CALL ADD_CITY("Cundinamarca","Manta");
CALL ADD_CITY("Cundinamarca","Medina");
CALL ADD_CITY("Cundinamarca","Mosquera");
CALL ADD_CITY("Cundinamarca","Nariño");
CALL ADD_CITY("Cundinamarca","Nemocón");
CALL ADD_CITY("Cundinamarca","Nilo");
CALL ADD_CITY("Cundinamarca","Nimaima");
CALL ADD_CITY("Cundinamarca","Nocaima");
CALL ADD_CITY("Cundinamarca","Pacho");
CALL ADD_CITY("Cundinamarca","Paime");
CALL ADD_CITY("Cundinamarca","Pandi");
CALL ADD_CITY("Cundinamarca","Paratebueno");
CALL ADD_CITY("Cundinamarca","Pasca");
CALL ADD_CITY("Cundinamarca","Puerto Salgar");
CALL ADD_CITY("Cundinamarca","Pulí");
CALL ADD_CITY("Cundinamarca","Quebradanegra");
CALL ADD_CITY("Cundinamarca","Quetame");
CALL ADD_CITY("Cundinamarca","Quipile");
CALL ADD_CITY("Cundinamarca","Ricaurte");
CALL ADD_CITY("Cundinamarca","San Antonio del Tequendama");
CALL ADD_CITY("Cundinamarca","San Bernardo");
CALL ADD_CITY("Cundinamarca","San Cayetano");
CALL ADD_CITY("Cundinamarca","San Francisco");
CALL ADD_CITY("Cundinamarca","San Juan de Río Seco");
CALL ADD_CITY("Cundinamarca","Sasaima");
CALL ADD_CITY("Cundinamarca","Sesquilé");
CALL ADD_CITY("Cundinamarca","Sibaté");
CALL ADD_CITY("Cundinamarca","Silvania");
CALL ADD_CITY("Cundinamarca","Simijaca");
CALL ADD_CITY("Cundinamarca","Soacha");
CALL ADD_CITY("Cundinamarca","Sopó");
CALL ADD_CITY("Cundinamarca","Subachoque");
CALL ADD_CITY("Cundinamarca","Suesca");
CALL ADD_CITY("Cundinamarca","Supatá");
CALL ADD_CITY("Cundinamarca","Susa");
CALL ADD_CITY("Cundinamarca","Sutatausa");
CALL ADD_CITY("Cundinamarca","Tabio");
CALL ADD_CITY("Cundinamarca","Tausa");
CALL ADD_CITY("Cundinamarca","Tena");
CALL ADD_CITY("Cundinamarca","Tenjo");
CALL ADD_CITY("Cundinamarca","Tibacuy");
CALL ADD_CITY("Cundinamarca","Tibirita");
CALL ADD_CITY("Cundinamarca","Tocaima");
CALL ADD_CITY("Cundinamarca","Tocancipá");
CALL ADD_CITY("Cundinamarca","Topaipí");
CALL ADD_CITY("Cundinamarca","Ubalá");
CALL ADD_CITY("Cundinamarca","Ubaque");
CALL ADD_CITY("Cundinamarca","Une");
CALL ADD_CITY("Cundinamarca","Útica");
CALL ADD_CITY("Cundinamarca","Venecia");
CALL ADD_CITY("Cundinamarca","Vergara");
CALL ADD_CITY("Cundinamarca","Vianí");
CALL ADD_CITY("Cundinamarca","Villa de San Diego de Ubate");
CALL ADD_CITY("Cundinamarca","Villagómez");
CALL ADD_CITY("Cundinamarca","Villapinzón");
CALL ADD_CITY("Cundinamarca","Villeta");
CALL ADD_CITY("Cundinamarca","Viotá");
CALL ADD_CITY("Cundinamarca","Yacopí");
CALL ADD_CITY("Cundinamarca","Zipacón");
CALL ADD_CITY("Cundinamarca","Zipaquirá");
CALL ADD_CITY("Norte de Santander","Abrego");
CALL ADD_CITY("Norte de Santander","Arboledas");
CALL ADD_CITY("Norte de Santander","Bochalema");
CALL ADD_CITY("Norte de Santander","Bucarasica");
CALL ADD_CITY("Norte de Santander","Cachirá");
CALL ADD_CITY("Norte de Santander","Cácota");
CALL ADD_CITY("Norte de Santander","Chinácota");
CALL ADD_CITY("Norte de Santander","Chitagá");
CALL ADD_CITY("Norte de Santander","Convención");
CALL ADD_CITY("Norte de Santander","Cúcuta");
CALL ADD_CITY("Norte de Santander","Cucutilla");
CALL ADD_CITY("Norte de Santander","Durania");
CALL ADD_CITY("Norte de Santander","El Carmen");
CALL ADD_CITY("Norte de Santander","El Tarra");
CALL ADD_CITY("Norte de Santander","El Zulia");
CALL ADD_CITY("Norte de Santander","Gramalote");
CALL ADD_CITY("Norte de Santander","Hacarí");
CALL ADD_CITY("Norte de Santander","Herrán");
CALL ADD_CITY("Norte de Santander","La Esperanza");
CALL ADD_CITY("Norte de Santander","La Playa");
CALL ADD_CITY("Norte de Santander","Labateca");
CALL ADD_CITY("Norte de Santander","Los Patios");
CALL ADD_CITY("Norte de Santander","Lourdes");
CALL ADD_CITY("Norte de Santander","Mutiscua");
CALL ADD_CITY("Norte de Santander","Ocaña");
CALL ADD_CITY("Norte de Santander","Pamplona");
CALL ADD_CITY("Norte de Santander","Pamplonita");
CALL ADD_CITY("Norte de Santander","Puerto Santander");
CALL ADD_CITY("Norte de Santander","Ragonvalia");
CALL ADD_CITY("Norte de Santander","Salazar");
CALL ADD_CITY("Norte de Santander","San Calixto");
CALL ADD_CITY("Norte de Santander","San Cayetano");
CALL ADD_CITY("Norte de Santander","Santiago");
CALL ADD_CITY("Norte de Santander","Sardinata");
CALL ADD_CITY("Norte de Santander","Silos");
CALL ADD_CITY("Norte de Santander","Teorama");
CALL ADD_CITY("Norte de Santander","Tibú");
CALL ADD_CITY("Norte de Santander","Toledo");
CALL ADD_CITY("Norte de Santander","Villa Caro");
CALL ADD_CITY("Norte de Santander","Villa del Rosario");
CALL ADD_CITY("Santander","Aguada");
CALL ADD_CITY("Santander","Albania");
CALL ADD_CITY("Santander","Aratoca");
CALL ADD_CITY("Santander","Barbosa");
CALL ADD_CITY("Santander","Barichara");
CALL ADD_CITY("Santander","Barrancabermeja");
CALL ADD_CITY("Santander","Betulia");
CALL ADD_CITY("Santander","Bolívar");
CALL ADD_CITY("Santander","Bucaramanga");
CALL ADD_CITY("Santander","Cabrera");
CALL ADD_CITY("Santander","California");
CALL ADD_CITY("Santander","Capitanejo");
CALL ADD_CITY("Santander","Carcasí");
CALL ADD_CITY("Santander","Cepitá");
CALL ADD_CITY("Santander","Cerrito");
CALL ADD_CITY("Santander","Charalá");
CALL ADD_CITY("Santander","Charta");
CALL ADD_CITY("Santander","Chimá");
CALL ADD_CITY("Santander","Chipatá");
CALL ADD_CITY("Santander","Cimitarra");
CALL ADD_CITY("Santander","Concepción");
CALL ADD_CITY("Santander","Confines");
CALL ADD_CITY("Santander","Contratación");
CALL ADD_CITY("Santander","Coromoro");
CALL ADD_CITY("Santander","Curití");
CALL ADD_CITY("Santander","El Carmen de Chucurí");
CALL ADD_CITY("Santander","El Guacamayo");
CALL ADD_CITY("Santander","El Peñón");
CALL ADD_CITY("Santander","El Playón");
CALL ADD_CITY("Santander","Encino");
CALL ADD_CITY("Santander","Enciso");
CALL ADD_CITY("Santander","Florián");
CALL ADD_CITY("Santander","Floridablanca");
CALL ADD_CITY("Santander","Galán");
CALL ADD_CITY("Santander","Gambita");
CALL ADD_CITY("Santander","Girón");
CALL ADD_CITY("Santander","Guaca");
CALL ADD_CITY("Santander","Guadalupe");
CALL ADD_CITY("Santander","Guapotá");
CALL ADD_CITY("Santander","Guavatá");
CALL ADD_CITY("Santander","Güepsa");
CALL ADD_CITY("Santander","Hato");
CALL ADD_CITY("Santander","Jesús María");
CALL ADD_CITY("Santander","Jordán");
CALL ADD_CITY("Santander","La Belleza");
CALL ADD_CITY("Santander","La Paz");
CALL ADD_CITY("Santander","Landázuri");
CALL ADD_CITY("Santander","Lebríja");
CALL ADD_CITY("Santander","Los Santos");
CALL ADD_CITY("Santander","Macaravita");
CALL ADD_CITY("Santander","Málaga");
CALL ADD_CITY("Santander","Matanza");
CALL ADD_CITY("Santander","Mogotes");
CALL ADD_CITY("Santander","Molagavita");
CALL ADD_CITY("Santander","Ocamonte");
CALL ADD_CITY("Santander","Oiba");
CALL ADD_CITY("Santander","Onzaga");
CALL ADD_CITY("Santander","Palmar");
CALL ADD_CITY("Santander","Palmas del Socorro");
CALL ADD_CITY("Santander","Páramo");
CALL ADD_CITY("Santander","Piedecuesta");
CALL ADD_CITY("Santander","Pinchote");
CALL ADD_CITY("Santander","Puente Nacional");
CALL ADD_CITY("Santander","Puerto Parra");
CALL ADD_CITY("Santander","Puerto Wilches");
CALL ADD_CITY("Santander","Rionegro");
CALL ADD_CITY("Santander","Sabana de Torres");
CALL ADD_CITY("Santander","San Andrés");
CALL ADD_CITY("Santander","San Benito");
CALL ADD_CITY("Santander","San Gil");
CALL ADD_CITY("Santander","San Joaquín");
CALL ADD_CITY("Santander","San José de Miranda");
CALL ADD_CITY("Santander","San Miguel");
CALL ADD_CITY("Santander","San Vicente de Chucurí");
CALL ADD_CITY("Santander","Santa Bárbara");
CALL ADD_CITY("Santander","Santa Helena del Opón");
CALL ADD_CITY("Santander","Simacota");
CALL ADD_CITY("Santander","Socorro");
CALL ADD_CITY("Santander","Suaita");
CALL ADD_CITY("Santander","Sucre");
CALL ADD_CITY("Santander","Suratá");
CALL ADD_CITY("Santander","Tona");
CALL ADD_CITY("Santander","Valle de San José");
CALL ADD_CITY("Santander","Vélez");
CALL ADD_CITY("Santander","Vetas");
CALL ADD_CITY("Santander","Villanueva");
CALL ADD_CITY("Santander","Zapatoca");
CALL ADD_CITY("Amazonas","El Encanto");
CALL ADD_CITY("Amazonas","La Chorrera");
CALL ADD_CITY("Amazonas","La Pedrera");
CALL ADD_CITY("Amazonas","La Victoria");
CALL ADD_CITY("Amazonas","Leticia");
CALL ADD_CITY("Amazonas","Miriti Paraná");
CALL ADD_CITY("Amazonas","Puerto Alegría");
CALL ADD_CITY("Amazonas","Puerto Arica");
CALL ADD_CITY("Amazonas","Puerto Nariño");
CALL ADD_CITY("Amazonas","Puerto Santander");
CALL ADD_CITY("Amazonas","Tarapacá");
CALL ADD_CITY("Caquetá","Albania");
CALL ADD_CITY("Caquetá","Belén de Los Andaquies");
CALL ADD_CITY("Caquetá","Cartagena del Chairá");
CALL ADD_CITY("Caquetá","Curillo");
CALL ADD_CITY("Caquetá","El Doncello");
CALL ADD_CITY("Caquetá","El Paujil");
CALL ADD_CITY("Caquetá","Florencia");
CALL ADD_CITY("Caquetá","La Montañita");
CALL ADD_CITY("Caquetá","Milán");
CALL ADD_CITY("Caquetá","Morelia");
CALL ADD_CITY("Caquetá","Puerto Rico");
CALL ADD_CITY("Caquetá","San José del Fragua");
CALL ADD_CITY("Caquetá","San Vicente del Caguán");
CALL ADD_CITY("Caquetá","Solano");
CALL ADD_CITY("Caquetá","Solita");
CALL ADD_CITY("Caquetá","Valparaíso");
CALL ADD_CITY("Huila","Acevedo");
CALL ADD_CITY("Huila","Agrado");
CALL ADD_CITY("Huila","Aipe");
CALL ADD_CITY("Huila","Algeciras");
CALL ADD_CITY("Huila","Altamira");
CALL ADD_CITY("Huila","Baraya");
CALL ADD_CITY("Huila","Campoalegre");
CALL ADD_CITY("Huila","Colombia");
CALL ADD_CITY("Huila","Elías");
CALL ADD_CITY("Huila","Garzón");
CALL ADD_CITY("Huila","Gigante");
CALL ADD_CITY("Huila","Guadalupe");
CALL ADD_CITY("Huila","Hobo");
CALL ADD_CITY("Huila","Iquira");
CALL ADD_CITY("Huila","Isnos");
CALL ADD_CITY("Huila","La Argentina");
CALL ADD_CITY("Huila","La Plata");
CALL ADD_CITY("Huila","Nátaga");
CALL ADD_CITY("Huila","Neiva");
CALL ADD_CITY("Huila","Oporapa");
CALL ADD_CITY("Huila","Paicol");
CALL ADD_CITY("Huila","Palermo");
CALL ADD_CITY("Huila","Palestina");
CALL ADD_CITY("Huila","Pital");
CALL ADD_CITY("Huila","Pitalito");
CALL ADD_CITY("Huila","Rivera");
CALL ADD_CITY("Huila","Saladoblanco");
CALL ADD_CITY("Huila","San Agustín");
CALL ADD_CITY("Huila","Santa María");
CALL ADD_CITY("Huila","Suaza");
CALL ADD_CITY("Huila","Tarqui");
CALL ADD_CITY("Huila","Tello");
CALL ADD_CITY("Huila","Teruel");
CALL ADD_CITY("Huila","Tesalia");
CALL ADD_CITY("Huila","Timaná");
CALL ADD_CITY("Huila","Villavieja");
CALL ADD_CITY("Huila","Yaguará");
CALL ADD_CITY("Putumayo","Colón");
CALL ADD_CITY("Putumayo","Leguízamo");
CALL ADD_CITY("Putumayo","Mocoa");
CALL ADD_CITY("Putumayo","Orito");
CALL ADD_CITY("Putumayo","Puerto Asís");
CALL ADD_CITY("Putumayo","Puerto Caicedo");
CALL ADD_CITY("Putumayo","Puerto Guzmán");
CALL ADD_CITY("Putumayo","San Francisco");
CALL ADD_CITY("Putumayo","San Miguel");
CALL ADD_CITY("Putumayo","Santiago");
CALL ADD_CITY("Putumayo","Sibundoy");
CALL ADD_CITY("Putumayo","Valle de Guamez");
CALL ADD_CITY("Putumayo","Villagarzón");
CALL ADD_CITY("Tolima","Alpujarra");
CALL ADD_CITY("Tolima","Alvarado");
CALL ADD_CITY("Tolima","Ambalema");
CALL ADD_CITY("Tolima","Anzoátegui");
CALL ADD_CITY("Tolima","Armero");
CALL ADD_CITY("Tolima","Ataco");
CALL ADD_CITY("Tolima","Cajamarca");
CALL ADD_CITY("Tolima","Carmen de Apicala");
CALL ADD_CITY("Tolima","Casabianca");
CALL ADD_CITY("Tolima","Chaparral");
CALL ADD_CITY("Tolima","Coello");
CALL ADD_CITY("Tolima","Coyaima");
CALL ADD_CITY("Tolima","Cunday");
CALL ADD_CITY("Tolima","Dolores");
CALL ADD_CITY("Tolima","Espinal");
CALL ADD_CITY("Tolima","Falan");
CALL ADD_CITY("Tolima","Flandes");
CALL ADD_CITY("Tolima","Fresno");
CALL ADD_CITY("Tolima","Guamo");
CALL ADD_CITY("Tolima","Herveo");
CALL ADD_CITY("Tolima","Honda");
CALL ADD_CITY("Tolima","Ibagué");
CALL ADD_CITY("Tolima","Icononzo");
CALL ADD_CITY("Tolima","Lérida");
CALL ADD_CITY("Tolima","Líbano");
CALL ADD_CITY("Tolima","Mariquita");
CALL ADD_CITY("Tolima","Melgar");
CALL ADD_CITY("Tolima","Murillo");
CALL ADD_CITY("Tolima","Natagaima");
CALL ADD_CITY("Tolima","Ortega");
CALL ADD_CITY("Tolima","Palocabildo");
CALL ADD_CITY("Tolima","Piedras");
CALL ADD_CITY("Tolima","Planadas");
CALL ADD_CITY("Tolima","Prado");
CALL ADD_CITY("Tolima","Purificación");
CALL ADD_CITY("Tolima","Rio Blanco");
CALL ADD_CITY("Tolima","Roncesvalles");
CALL ADD_CITY("Tolima","Rovira");
CALL ADD_CITY("Tolima","Saldaña");
CALL ADD_CITY("Tolima","San Antonio");
CALL ADD_CITY("Tolima","San Luis");
CALL ADD_CITY("Tolima","Santa Isabel");
CALL ADD_CITY("Tolima","Suárez");
CALL ADD_CITY("Tolima","Valle de San Juan");
CALL ADD_CITY("Tolima","Venadillo");
CALL ADD_CITY("Tolima","Villahermosa");
CALL ADD_CITY("Tolima","Villarrica");
CALL ADD_CITY("Antioquia","Abejorral");
CALL ADD_CITY("Antioquia","Abriaquí");
CALL ADD_CITY("Antioquia","Alejandría");
CALL ADD_CITY("Antioquia","Amagá");
CALL ADD_CITY("Antioquia","Amalfi");
CALL ADD_CITY("Antioquia","Andes");
CALL ADD_CITY("Antioquia","Angelópolis");
CALL ADD_CITY("Antioquia","Angostura");
CALL ADD_CITY("Antioquia","Anorí");
CALL ADD_CITY("Antioquia","Anza");
CALL ADD_CITY("Antioquia","Apartadó");
CALL ADD_CITY("Antioquia","Arboletes");
CALL ADD_CITY("Antioquia","Argelia");
CALL ADD_CITY("Antioquia","Armenia");
CALL ADD_CITY("Antioquia","Barbosa");
CALL ADD_CITY("Antioquia","Bello");
CALL ADD_CITY("Antioquia","Belmira");
CALL ADD_CITY("Antioquia","Betania");
CALL ADD_CITY("Antioquia","Betulia");
CALL ADD_CITY("Antioquia","Briceño");
CALL ADD_CITY("Antioquia","Buriticá");
CALL ADD_CITY("Antioquia","Cáceres");
CALL ADD_CITY("Antioquia","Caicedo");
CALL ADD_CITY("Antioquia","Caldas");
CALL ADD_CITY("Antioquia","Campamento");
CALL ADD_CITY("Antioquia","Cañasgordas");
CALL ADD_CITY("Antioquia","Caracolí");
CALL ADD_CITY("Antioquia","Caramanta");
CALL ADD_CITY("Antioquia","Carepa");
CALL ADD_CITY("Antioquia","Carolina");
CALL ADD_CITY("Antioquia","Caucasia");
CALL ADD_CITY("Antioquia","Chigorodó");
CALL ADD_CITY("Antioquia","Cisneros");
CALL ADD_CITY("Antioquia","Ciudad Bolívar");
CALL ADD_CITY("Antioquia","Cocorná");
CALL ADD_CITY("Antioquia","Concepción");
CALL ADD_CITY("Antioquia","Concordia");
CALL ADD_CITY("Antioquia","Copacabana");
CALL ADD_CITY("Antioquia","Dabeiba");
CALL ADD_CITY("Antioquia","Don Matías");
CALL ADD_CITY("Antioquia","Ebéjico");
CALL ADD_CITY("Antioquia","El Bagre");
CALL ADD_CITY("Antioquia","El Carmen de Viboral");
CALL ADD_CITY("Antioquia","El Santuario");
CALL ADD_CITY("Antioquia","Entrerrios");
CALL ADD_CITY("Antioquia","Envigado");
CALL ADD_CITY("Antioquia","Fredonia");
CALL ADD_CITY("Antioquia","Frontino");
CALL ADD_CITY("Antioquia","Giraldo");
CALL ADD_CITY("Antioquia","Girardota");
CALL ADD_CITY("Antioquia","Gómez Plata");
CALL ADD_CITY("Antioquia","Granada");
CALL ADD_CITY("Antioquia","Guadalupe");
CALL ADD_CITY("Antioquia","Guarne");
CALL ADD_CITY("Antioquia","Guatapé");
CALL ADD_CITY("Antioquia","Heliconia");
CALL ADD_CITY("Antioquia","Hispania");
CALL ADD_CITY("Antioquia","Itagui");
CALL ADD_CITY("Antioquia","Ituango");
CALL ADD_CITY("Antioquia","Jardín");
CALL ADD_CITY("Antioquia","Jericó");
CALL ADD_CITY("Antioquia","La Ceja");
CALL ADD_CITY("Antioquia","La Estrella");
CALL ADD_CITY("Antioquia","La Pintada");
CALL ADD_CITY("Antioquia","La Unión");
CALL ADD_CITY("Antioquia","Liborina");
CALL ADD_CITY("Antioquia","Maceo");
CALL ADD_CITY("Antioquia","Marinilla");
CALL ADD_CITY("Antioquia","Medellín");
CALL ADD_CITY("Antioquia","Montebello");
CALL ADD_CITY("Antioquia","Murindó");
CALL ADD_CITY("Antioquia","Mutatá");
CALL ADD_CITY("Antioquia","Nariño");
CALL ADD_CITY("Antioquia","Nechí");
CALL ADD_CITY("Antioquia","Necoclí");
CALL ADD_CITY("Antioquia","Olaya");
CALL ADD_CITY("Antioquia","Peñol");
CALL ADD_CITY("Antioquia","Peque");
CALL ADD_CITY("Antioquia","Pueblorrico");
CALL ADD_CITY("Antioquia","Puerto Berrío");
CALL ADD_CITY("Antioquia","Puerto Nare");
CALL ADD_CITY("Antioquia","Puerto Triunfo");
CALL ADD_CITY("Antioquia","Remedios");
CALL ADD_CITY("Antioquia","Retiro");
CALL ADD_CITY("Antioquia","Rionegro");
CALL ADD_CITY("Antioquia","Sabanalarga");
CALL ADD_CITY("Antioquia","Sabaneta");
CALL ADD_CITY("Antioquia","Salgar");
CALL ADD_CITY("Antioquia","San Andrés de Cuerquía");
CALL ADD_CITY("Antioquia","San Carlos");
CALL ADD_CITY("Antioquia","San Francisco");
CALL ADD_CITY("Antioquia","San Jerónimo");
CALL ADD_CITY("Antioquia","San José de La Montaña");
CALL ADD_CITY("Antioquia","San Juan de Urabá");
CALL ADD_CITY("Antioquia","San Luis");
CALL ADD_CITY("Antioquia","San Pedro");
CALL ADD_CITY("Antioquia","San Pedro de Uraba");
CALL ADD_CITY("Antioquia","San Rafael");
CALL ADD_CITY("Antioquia","San Roque");
CALL ADD_CITY("Antioquia","San Vicente");
CALL ADD_CITY("Antioquia","Santa Bárbara");
CALL ADD_CITY("Antioquia","Santa Rosa de Osos");
CALL ADD_CITY("Antioquia","Santafé de Antioquia");
CALL ADD_CITY("Antioquia","Santo Domingo");
CALL ADD_CITY("Antioquia","Segovia");
CALL ADD_CITY("Antioquia","Sonsón");
CALL ADD_CITY("Antioquia","Sopetrán");
CALL ADD_CITY("Antioquia","Támesis");
CALL ADD_CITY("Antioquia","Tarazá");
CALL ADD_CITY("Antioquia","Tarso");
CALL ADD_CITY("Antioquia","Titiribí");
CALL ADD_CITY("Antioquia","Toledo");
CALL ADD_CITY("Antioquia","Turbo");
CALL ADD_CITY("Antioquia","Uramita");
CALL ADD_CITY("Antioquia","Urrao");
CALL ADD_CITY("Antioquia","Valdivia");
CALL ADD_CITY("Antioquia","Valparaíso");
CALL ADD_CITY("Antioquia","Vegachí");
CALL ADD_CITY("Antioquia","Venecia");
CALL ADD_CITY("Antioquia","Vigía del Fuerte");
CALL ADD_CITY("Antioquia","Yalí");
CALL ADD_CITY("Antioquia","Yarumal");
CALL ADD_CITY("Antioquia","Yolombó");
CALL ADD_CITY("Antioquia","Yondó");
CALL ADD_CITY("Antioquia","Zaragoza");
CALL ADD_CITY("Caldas","Aguadas");
CALL ADD_CITY("Caldas","Anserma");
CALL ADD_CITY("Caldas","Aranzazu");
CALL ADD_CITY("Caldas","Belalcázar");
CALL ADD_CITY("Caldas","Chinchiná");
CALL ADD_CITY("Caldas","Filadelfia");
CALL ADD_CITY("Caldas","La Dorada");
CALL ADD_CITY("Caldas","La Merced");
CALL ADD_CITY("Caldas","Manizales");
CALL ADD_CITY("Caldas","Manzanares");
CALL ADD_CITY("Caldas","Marmato");
CALL ADD_CITY("Caldas","Marquetalia");
CALL ADD_CITY("Caldas","Marulanda");
CALL ADD_CITY("Caldas","Neira");
CALL ADD_CITY("Caldas","Norcasia");
CALL ADD_CITY("Caldas","Pácora");
CALL ADD_CITY("Caldas","Palestina");
CALL ADD_CITY("Caldas","Pensilvania");
CALL ADD_CITY("Caldas","Riosucio");
CALL ADD_CITY("Caldas","Risaralda");
CALL ADD_CITY("Caldas","Salamina");
CALL ADD_CITY("Caldas","Samaná");
CALL ADD_CITY("Caldas","San José");
CALL ADD_CITY("Caldas","Supía");
CALL ADD_CITY("Caldas","Victoria");
CALL ADD_CITY("Caldas","Villamaría");
CALL ADD_CITY("Caldas","Viterbo");
CALL ADD_CITY("Quindío","Armenia");
CALL ADD_CITY("Quindío","Buenavista");
CALL ADD_CITY("Quindío","Calarcá");
CALL ADD_CITY("Quindío","Circasia");
CALL ADD_CITY("Quindío","Córdoba");
CALL ADD_CITY("Quindío","Filandia");
CALL ADD_CITY("Quindío","Génova");
CALL ADD_CITY("Quindío","La Tebaida");
CALL ADD_CITY("Quindío","Montenegro");
CALL ADD_CITY("Quindío","Pijao");
CALL ADD_CITY("Quindío","Quimbaya");
CALL ADD_CITY("Quindío","Salento");
CALL ADD_CITY("Risaralda","Apía");
CALL ADD_CITY("Risaralda","Balboa");
CALL ADD_CITY("Risaralda","Belén de Umbría");
CALL ADD_CITY("Risaralda","Dosquebradas");
CALL ADD_CITY("Risaralda","Guática");
CALL ADD_CITY("Risaralda","La Celia");
CALL ADD_CITY("Risaralda","La Virginia");
CALL ADD_CITY("Risaralda","Marsella");
CALL ADD_CITY("Risaralda","Mistrató");
CALL ADD_CITY("Risaralda","Pereira");
CALL ADD_CITY("Risaralda","Pueblo Rico");
CALL ADD_CITY("Risaralda","Quinchía");
CALL ADD_CITY("Risaralda","Santa Rosa de Cabal");
CALL ADD_CITY("Risaralda","Santuario");
CALL ADD_CITY("Arauca","Arauca");
CALL ADD_CITY("Arauca","Arauquita");
CALL ADD_CITY("Arauca","Cravo Norte");
CALL ADD_CITY("Arauca","Fortul");
CALL ADD_CITY("Arauca","Puerto Rondón");
CALL ADD_CITY("Arauca","Saravena");
CALL ADD_CITY("Arauca","Tame");
CALL ADD_CITY("Casanare","Aguazul");
CALL ADD_CITY("Casanare","Chámeza");
CALL ADD_CITY("Casanare","Hato Corozal");
CALL ADD_CITY("Casanare","La Salina");
CALL ADD_CITY("Casanare","Maní");
CALL ADD_CITY("Casanare","Monterrey");
CALL ADD_CITY("Casanare","Nunchía");
CALL ADD_CITY("Casanare","Orocué");
CALL ADD_CITY("Casanare","Paz de Ariporo");
CALL ADD_CITY("Casanare","Pore");
CALL ADD_CITY("Casanare","Recetor");
CALL ADD_CITY("Casanare","Sabanalarga");
CALL ADD_CITY("Casanare","Sácama");
CALL ADD_CITY("Casanare","San Luis de Gaceno");
CALL ADD_CITY("Casanare","Támara");
CALL ADD_CITY("Casanare","Tauramena");
CALL ADD_CITY("Casanare","Trinidad");
CALL ADD_CITY("Casanare","Villanueva");
CALL ADD_CITY("Casanare","Yopal");
CALL ADD_CITY("Guainía","Barranco Minas");
CALL ADD_CITY("Guainía","Cacahual");
CALL ADD_CITY("Guainía","Inírida");
CALL ADD_CITY("Guainía","La Guadalupe");
CALL ADD_CITY("Guainía","Mapiripana");
CALL ADD_CITY("Guainía","Morichal");
CALL ADD_CITY("Guainía","Pana Pana");
CALL ADD_CITY("Guainía","Puerto Colombia");
CALL ADD_CITY("Guainía","San Felipe");
CALL ADD_CITY("Guaviare","Calamar");
CALL ADD_CITY("Guaviare","El Retorno");
CALL ADD_CITY("Guaviare","Miraflores");
CALL ADD_CITY("Guaviare","San José del Guaviare");
CALL ADD_CITY("Meta","Acacias");
CALL ADD_CITY("Meta","Barranca de Upía");
CALL ADD_CITY("Meta","Cabuyaro");
CALL ADD_CITY("Meta","Castilla la Nueva");
CALL ADD_CITY("Meta","Cubarral");
CALL ADD_CITY("Meta","Cumaral");
CALL ADD_CITY("Meta","El Calvario");
CALL ADD_CITY("Meta","El Castillo");
CALL ADD_CITY("Meta","El Dorado");
CALL ADD_CITY("Meta","Fuente de Oro");
CALL ADD_CITY("Meta","Granada");
CALL ADD_CITY("Meta","Guamal");
CALL ADD_CITY("Meta","La Macarena");
CALL ADD_CITY("Meta","Lejanías");
CALL ADD_CITY("Meta","Mapiripán");
CALL ADD_CITY("Meta","Mesetas");
CALL ADD_CITY("Meta","Puerto Concordia");
CALL ADD_CITY("Meta","Puerto Gaitán");
CALL ADD_CITY("Meta","Puerto Lleras");
CALL ADD_CITY("Meta","Puerto López");
CALL ADD_CITY("Meta","Puerto Rico");
CALL ADD_CITY("Meta","Restrepo");
CALL ADD_CITY("Meta","San Carlos de Guaroa");
CALL ADD_CITY("Meta","San Juan de Arama");
CALL ADD_CITY("Meta","San Juanito");
CALL ADD_CITY("Meta","San Martín");
CALL ADD_CITY("Meta","Uribe");
CALL ADD_CITY("Meta","Villavicencio");
CALL ADD_CITY("Meta","Vista Hermosa");
CALL ADD_CITY("Vaupés","Caruru");
CALL ADD_CITY("Vaupés","Mitú");
CALL ADD_CITY("Vaupés","Pacoa");
CALL ADD_CITY("Vaupés","Papunaua");
CALL ADD_CITY("Vaupés","Taraira");
CALL ADD_CITY("Vaupés","Yavaraté");
CALL ADD_CITY("Vichada","Cumaribo");
CALL ADD_CITY("Vichada","La Primavera");
CALL ADD_CITY("Vichada","Puerto Carreño");
CALL ADD_CITY("Vichada","Santa Rosalía");
CALL ADD_CITY("Cauca","Almaguer");
CALL ADD_CITY("Cauca","Argelia");
CALL ADD_CITY("Cauca","Balboa");
CALL ADD_CITY("Cauca","Bolívar");
CALL ADD_CITY("Cauca","Buenos Aires");
CALL ADD_CITY("Cauca","Cajibío");
CALL ADD_CITY("Cauca","Caldono");
CALL ADD_CITY("Cauca","Caloto");
CALL ADD_CITY("Cauca","Corinto");
CALL ADD_CITY("Cauca","El Tambo");
CALL ADD_CITY("Cauca","Florencia");
CALL ADD_CITY("Cauca","Guachené");
CALL ADD_CITY("Cauca","Guapi");
CALL ADD_CITY("Cauca","Inzá");
CALL ADD_CITY("Cauca","Jambaló");
CALL ADD_CITY("Cauca","La Sierra");
CALL ADD_CITY("Cauca","La Vega");
CALL ADD_CITY("Cauca","López");
CALL ADD_CITY("Cauca","Mercaderes");
CALL ADD_CITY("Cauca","Miranda");
CALL ADD_CITY("Cauca","Morales");
CALL ADD_CITY("Cauca","Padilla");
CALL ADD_CITY("Cauca","Páez");
CALL ADD_CITY("Cauca","Patía");
CALL ADD_CITY("Cauca","Piamonte");
CALL ADD_CITY("Cauca","Piendamó");
CALL ADD_CITY("Cauca","Popayán");
CALL ADD_CITY("Cauca","Puerto Tejada");
CALL ADD_CITY("Cauca","Puracé");
CALL ADD_CITY("Cauca","Rosas");
CALL ADD_CITY("Cauca","San Sebastián");
CALL ADD_CITY("Cauca","Santa Rosa");
CALL ADD_CITY("Cauca","Santander de Quilichao");
CALL ADD_CITY("Cauca","Silvia");
CALL ADD_CITY("Cauca","Sotara");
CALL ADD_CITY("Cauca","Suárez");
CALL ADD_CITY("Cauca","Sucre");
CALL ADD_CITY("Cauca","Timbío");
CALL ADD_CITY("Cauca","Timbiquí");
CALL ADD_CITY("Cauca","Toribio");
CALL ADD_CITY("Cauca","Totoró");
CALL ADD_CITY("Cauca","Villa Rica");
CALL ADD_CITY("Chocó","Acandí");
CALL ADD_CITY("Chocó","Alto Baudo");
CALL ADD_CITY("Chocó","Atrato");
CALL ADD_CITY("Chocó","Bagadó");
CALL ADD_CITY("Chocó","Bahía Solano");
CALL ADD_CITY("Chocó","Bajo Baudó");
CALL ADD_CITY("Chocó","Belén de Bajira");
CALL ADD_CITY("Chocó","Bojaya");
CALL ADD_CITY("Chocó","Carmen del Darien");
CALL ADD_CITY("Chocó","Cértegui");
CALL ADD_CITY("Chocó","Condoto");
CALL ADD_CITY("Chocó","El Cantón del San Pablo");
CALL ADD_CITY("Chocó","El Carmen de Atrato");
CALL ADD_CITY("Chocó","El Litoral del San Juan");
CALL ADD_CITY("Chocó","Istmina");
CALL ADD_CITY("Chocó","Juradó");
CALL ADD_CITY("Chocó","Lloró");
CALL ADD_CITY("Chocó","Medio Atrato");
CALL ADD_CITY("Chocó","Medio Baudó");
CALL ADD_CITY("Chocó","Medio San Juan");
CALL ADD_CITY("Chocó","Nóvita");
CALL ADD_CITY("Chocó","Nuquí");
CALL ADD_CITY("Chocó","Quibdó");
CALL ADD_CITY("Chocó","Río Iro");
CALL ADD_CITY("Chocó","Río Quito");
CALL ADD_CITY("Chocó","Riosucio");
CALL ADD_CITY("Chocó","San José del Palmar");
CALL ADD_CITY("Chocó","Sipí");
CALL ADD_CITY("Chocó","Tadó");
CALL ADD_CITY("Chocó","Unguía");
CALL ADD_CITY("Chocó","Unión Panamericana");
CALL ADD_CITY("Nariño","Albán");
CALL ADD_CITY("Nariño","Aldana");
CALL ADD_CITY("Nariño","Ancuyá");
CALL ADD_CITY("Nariño","Arboleda");
CALL ADD_CITY("Nariño","Barbacoas");
CALL ADD_CITY("Nariño","Belén");
CALL ADD_CITY("Nariño","Buesaco");
CALL ADD_CITY("Nariño","Chachagüí");
CALL ADD_CITY("Nariño","Colón");
CALL ADD_CITY("Nariño","Consaca");
CALL ADD_CITY("Nariño","Contadero");
CALL ADD_CITY("Nariño","Córdoba");
CALL ADD_CITY("Nariño","Cuaspud");
CALL ADD_CITY("Nariño","Cumbal");
CALL ADD_CITY("Nariño","Cumbitara");
CALL ADD_CITY("Nariño","El Charco");
CALL ADD_CITY("Nariño","El Peñol");
CALL ADD_CITY("Nariño","El Rosario");
CALL ADD_CITY("Nariño","El Tablón de Gómez");
CALL ADD_CITY("Nariño","El Tambo");
CALL ADD_CITY("Nariño","Francisco Pizarro");
CALL ADD_CITY("Nariño","Funes");
CALL ADD_CITY("Nariño","Guachucal");
CALL ADD_CITY("Nariño","Guaitarilla");
CALL ADD_CITY("Nariño","Gualmatán");
CALL ADD_CITY("Nariño","Iles");
CALL ADD_CITY("Nariño","Imués");
CALL ADD_CITY("Nariño","Ipiales");
CALL ADD_CITY("Nariño","La Cruz");
CALL ADD_CITY("Nariño","La Florida");
CALL ADD_CITY("Nariño","La Llanada");
CALL ADD_CITY("Nariño","La Tola");
CALL ADD_CITY("Nariño","La Unión");
CALL ADD_CITY("Nariño","Leiva");
CALL ADD_CITY("Nariño","Linares");
CALL ADD_CITY("Nariño","Los Andes");
CALL ADD_CITY("Nariño","Magüí");
CALL ADD_CITY("Nariño","Mallama");
CALL ADD_CITY("Nariño","Mosquera");
CALL ADD_CITY("Nariño","Nariño");
CALL ADD_CITY("Nariño","Olaya Herrera");
CALL ADD_CITY("Nariño","Ospina");
CALL ADD_CITY("Nariño","Pasto");
CALL ADD_CITY("Nariño","Policarpa");
CALL ADD_CITY("Nariño","Potosí");
CALL ADD_CITY("Nariño","Providencia");
CALL ADD_CITY("Nariño","Puerres");
CALL ADD_CITY("Nariño","Pupiales");
CALL ADD_CITY("Nariño","Ricaurte");
CALL ADD_CITY("Nariño","Roberto Payán");
CALL ADD_CITY("Nariño","Samaniego");
CALL ADD_CITY("Nariño","San Andrés de Tumaco");
CALL ADD_CITY("Nariño","San Bernardo");
CALL ADD_CITY("Nariño","San Lorenzo");
CALL ADD_CITY("Nariño","San Pablo");
CALL ADD_CITY("Nariño","San Pedro de Cartago");
CALL ADD_CITY("Nariño","Sandoná");
CALL ADD_CITY("Nariño","Santa Bárbara");
CALL ADD_CITY("Nariño","Santacruz");
CALL ADD_CITY("Nariño","Sapuyes");
CALL ADD_CITY("Nariño","Taminango");
CALL ADD_CITY("Nariño","Tangua");
CALL ADD_CITY("Nariño","Túquerres");
CALL ADD_CITY("Nariño","Yacuanquer");
CALL ADD_CITY("Valle del Cauca","Alcalá");
CALL ADD_CITY("Valle del Cauca","Andalucía");
CALL ADD_CITY("Valle del Cauca","Ansermanuevo");
CALL ADD_CITY("Valle del Cauca","Argelia");
CALL ADD_CITY("Valle del Cauca","Bolívar");
CALL ADD_CITY("Valle del Cauca","Buenaventura");
CALL ADD_CITY("Valle del Cauca","Bugalagrande");
CALL ADD_CITY("Valle del Cauca","Caicedonia");
CALL ADD_CITY("Valle del Cauca","Cali");
CALL ADD_CITY("Valle del Cauca","Calima");
CALL ADD_CITY("Valle del Cauca","Candelaria");
CALL ADD_CITY("Valle del Cauca","Cartago");
CALL ADD_CITY("Valle del Cauca","Dagua");
CALL ADD_CITY("Valle del Cauca","El Águila");
CALL ADD_CITY("Valle del Cauca","El Cairo");
CALL ADD_CITY("Valle del Cauca","El Cerrito");
CALL ADD_CITY("Valle del Cauca","El Dovio");
CALL ADD_CITY("Valle del Cauca","Florida");
CALL ADD_CITY("Valle del Cauca","Ginebra");
CALL ADD_CITY("Valle del Cauca","Guacarí");
CALL ADD_CITY("Valle del Cauca","Guadalajara de Buga");
CALL ADD_CITY("Valle del Cauca","Jamundí");
CALL ADD_CITY("Valle del Cauca","La Cumbre");
CALL ADD_CITY("Valle del Cauca","La Unión");
CALL ADD_CITY("Valle del Cauca","La Victoria");
CALL ADD_CITY("Valle del Cauca","Obando");
CALL ADD_CITY("Valle del Cauca","Palmira");
CALL ADD_CITY("Valle del Cauca","Pradera");
CALL ADD_CITY("Valle del Cauca","Restrepo");
CALL ADD_CITY("Valle del Cauca","Riofrío");
CALL ADD_CITY("Valle del Cauca","Roldanillo");
CALL ADD_CITY("Valle del Cauca","San Pedro");
CALL ADD_CITY("Valle del Cauca","Sevilla");
CALL ADD_CITY("Valle del Cauca","Toro");
CALL ADD_CITY("Valle del Cauca","Trujillo");
CALL ADD_CITY("Valle del Cauca","Tuluá");
CALL ADD_CITY("Valle del Cauca","Ulloa");
CALL ADD_CITY("Valle del Cauca","Versalles");
CALL ADD_CITY("Valle del Cauca","Vijes");
CALL ADD_CITY("Valle del Cauca","Yotoco");
CALL ADD_CITY("Valle del Cauca","Yumbo");
CALL ADD_CITY("Valle del Cauca","Zarzal");